/**
 * DHL zone mapping: country code -> { rateKey, label }
 * Source: Zone Guide 2026.xlsx (DHL sheet)
 * Auto-synced with DHL_ZONE_COUNTRIES in options.ts
 */

import type { ZoneInfo } from './ups_zones';

const z = (rateKey: string, label: string): ZoneInfo => ({ rateKey, label });

export const DHL_ZONE_MAP: Record<string, ZoneInfo> = {
  // Z1: CN, HK, MO, SG, TW
  CN: z('Z1', 'Z1/Asia'),
  HK: z('Z1', 'Z1/Asia'),
  MO: z('Z1', 'Z1/Asia'),
  SG: z('Z1', 'Z1/Asia'),
  TW: z('Z1', 'Z1/Asia'),
  // Z2: JP
  JP: z('Z2', 'Z2/Japan'),
  // Z3: BN, ID, KH, LA, MM, MY, PH, TH, VN
  BN: z('Z3', 'Z3/SEA'),
  ID: z('Z3', 'Z3/SEA'),
  KH: z('Z3', 'Z3/SEA'),
  LA: z('Z3', 'Z3/SEA'),
  MM: z('Z3', 'Z3/SEA'),
  MY: z('Z3', 'Z3/SEA'),
  PH: z('Z3', 'Z3/SEA'),
  TH: z('Z3', 'Z3/SEA'),
  VN: z('Z3', 'Z3/SEA'),
  // Z4: AU, BD, IN, LK, NZ, PG, PK
  AU: z('Z4', 'Z4/Oceania'),
  BD: z('Z4', 'Z4/Oceania'),
  IN: z('Z4', 'Z4/Oceania'),
  LK: z('Z4', 'Z4/Oceania'),
  NZ: z('Z4', 'Z4/Oceania'),
  PG: z('Z4', 'Z4/Oceania'),
  PK: z('Z4', 'Z4/Oceania'),
  // Z5: CA, MX, US
  CA: z('Z5', 'Z5/Americas'),
  MX: z('Z5', 'Z5/Americas'),
  US: z('Z5', 'Z5/Americas'),
  // Z6 (37 countries)
  AD: z('Z6', 'Z6/Europe'),
  AT: z('Z6', 'Z6/Europe'),
  BE: z('Z6', 'Z6/Europe'),
  BG: z('Z6', 'Z6/Europe'),
  CH: z('Z6', 'Z6/Europe'),
  CY: z('Z6', 'Z6/Europe'),
  CZ: z('Z6', 'Z6/Europe'),
  DE: z('Z6', 'Z6/Europe'),
  DK: z('Z6', 'Z6/Europe'),
  EE: z('Z6', 'Z6/Europe'),
  ES: z('Z6', 'Z6/Europe'),
  FI: z('Z6', 'Z6/Europe'),
  FR: z('Z6', 'Z6/Europe'),
  GB: z('Z6', 'Z6/Europe'),
  GG: z('Z6', 'Z6/Europe'),
  GR: z('Z6', 'Z6/Europe'),
  HR: z('Z6', 'Z6/Europe'),
  HU: z('Z6', 'Z6/Europe'),
  IE: z('Z6', 'Z6/Europe'),
  IT: z('Z6', 'Z6/Europe'),
  JE: z('Z6', 'Z6/Europe'),
  LI: z('Z6', 'Z6/Europe'),
  LT: z('Z6', 'Z6/Europe'),
  LU: z('Z6', 'Z6/Europe'),
  LV: z('Z6', 'Z6/Europe'),
  MC: z('Z6', 'Z6/Europe'),
  MT: z('Z6', 'Z6/Europe'),
  NL: z('Z6', 'Z6/Europe'),
  NO: z('Z6', 'Z6/Europe'),
  PL: z('Z6', 'Z6/Europe'),
  PT: z('Z6', 'Z6/Europe'),
  RO: z('Z6', 'Z6/Europe'),
  SE: z('Z6', 'Z6/Europe'),
  SI: z('Z6', 'Z6/Europe'),
  SK: z('Z6', 'Z6/Europe'),
  SM: z('Z6', 'Z6/Europe'),
  VA: z('Z6', 'Z6/Europe'),
  // Z7 (16 countries)
  AE: z('Z7', 'Z7/ME-Balkans'),
  AL: z('Z7', 'Z7/ME-Balkans'),
  BA: z('Z7', 'Z7/ME-Balkans'),
  BH: z('Z7', 'Z7/ME-Balkans'),
  GI: z('Z7', 'Z7/ME-Balkans'),
  IC: z('Z7', 'Z7/ME-Balkans'),
  IL: z('Z7', 'Z7/ME-Balkans'),
  KV: z('Z7', 'Z7/ME-Balkans'),
  KW: z('Z7', 'Z7/ME-Balkans'),
  ME: z('Z7', 'Z7/ME-Balkans'),
  MK: z('Z7', 'Z7/ME-Balkans'),
  OM: z('Z7', 'Z7/ME-Balkans'),
  QA: z('Z7', 'Z7/ME-Balkans'),
  RS: z('Z7', 'Z7/ME-Balkans'),
  SA: z('Z7', 'Z7/ME-Balkans'),
  TR: z('Z7', 'Z7/ME-Balkans'),
  // Z8 (150+ countries)
  AF: z('Z8', 'Z8/Global'),
  AG: z('Z8', 'Z8/Global'),
  AI: z('Z8', 'Z8/Global'),
  AM: z('Z8', 'Z8/Global'),
  AO: z('Z8', 'Z8/Global'),
  AR: z('Z8', 'Z8/Global'),
  AS: z('Z8', 'Z8/Global'),
  AW: z('Z8', 'Z8/Global'),
  AZ: z('Z8', 'Z8/Global'),
  BB: z('Z8', 'Z8/Global'),
  BF: z('Z8', 'Z8/Global'),
  BI: z('Z8', 'Z8/Global'),
  BJ: z('Z8', 'Z8/Global'),
  BM: z('Z8', 'Z8/Global'),
  BO: z('Z8', 'Z8/Global'),
  BR: z('Z8', 'Z8/Global'),
  BS: z('Z8', 'Z8/Global'),
  BT: z('Z8', 'Z8/Global'),
  XB: z('Z8', 'Z8/Global'),  // Bonaire (DHL code)
  BQ: z('Z8', 'Z8/Global'),  // Bonaire, St. Eustatius, Saba (ISO code)
  BW: z('Z8', 'Z8/Global'),
  BY: z('Z8', 'Z8/Global'),
  BZ: z('Z8', 'Z8/Global'),
  CD: z('Z8', 'Z8/Global'),
  CF: z('Z8', 'Z8/Global'),
  CG: z('Z8', 'Z8/Global'),
  CI: z('Z8', 'Z8/Global'),
  CK: z('Z8', 'Z8/Global'),
  CL: z('Z8', 'Z8/Global'),
  CM: z('Z8', 'Z8/Global'),
  CO: z('Z8', 'Z8/Global'),
  CR: z('Z8', 'Z8/Global'),
  CU: z('Z8', 'Z8/Global'),
  CV: z('Z8', 'Z8/Global'),
  DJ: z('Z8', 'Z8/Global'),
  DM: z('Z8', 'Z8/Global'),
  DO: z('Z8', 'Z8/Global'),
  DZ: z('Z8', 'Z8/Global'),
  EC: z('Z8', 'Z8/Global'),
  EG: z('Z8', 'Z8/Global'),
  ER: z('Z8', 'Z8/Global'),
  ET: z('Z8', 'Z8/Global'),
  FJ: z('Z8', 'Z8/Global'),
  FK: z('Z8', 'Z8/Global'),
  FM: z('Z8', 'Z8/Global'),
  FO: z('Z8', 'Z8/Global'),
  GA: z('Z8', 'Z8/Global'),
  GD: z('Z8', 'Z8/Global'),
  GE: z('Z8', 'Z8/Global'),
  GF: z('Z8', 'Z8/Global'),
  GH: z('Z8', 'Z8/Global'),
  GL: z('Z8', 'Z8/Global'),
  GM: z('Z8', 'Z8/Global'),
  GN: z('Z8', 'Z8/Global'),
  GP: z('Z8', 'Z8/Global'),
  GQ: z('Z8', 'Z8/Global'),
  GT: z('Z8', 'Z8/Global'),
  GU: z('Z8', 'Z8/Global'),
  GW: z('Z8', 'Z8/Global'),
  GY: z('Z8', 'Z8/Global'),
  HN: z('Z8', 'Z8/Global'),
  HT: z('Z8', 'Z8/Global'),
  IQ: z('Z8', 'Z8/Global'),
  IR: z('Z8', 'Z8/Global'),
  IS: z('Z8', 'Z8/Global'),
  JM: z('Z8', 'Z8/Global'),
  JO: z('Z8', 'Z8/Global'),
  KE: z('Z8', 'Z8/Global'),
  KG: z('Z8', 'Z8/Global'),
  KI: z('Z8', 'Z8/Global'),
  KM: z('Z8', 'Z8/Global'),
  KN: z('Z8', 'Z8/Global'),
  KP: z('Z8', 'Z8/Global'),
  KY: z('Z8', 'Z8/Global'),
  KZ: z('Z8', 'Z8/Global'),
  LB: z('Z8', 'Z8/Global'),
  LC: z('Z8', 'Z8/Global'),
  LR: z('Z8', 'Z8/Global'),
  LS: z('Z8', 'Z8/Global'),
  LY: z('Z8', 'Z8/Global'),
  MA: z('Z8', 'Z8/Global'),
  MD: z('Z8', 'Z8/Global'),
  MG: z('Z8', 'Z8/Global'),
  MH: z('Z8', 'Z8/Global'),
  ML: z('Z8', 'Z8/Global'),
  MN: z('Z8', 'Z8/Global'),
  MP: z('Z8', 'Z8/Global'),
  MQ: z('Z8', 'Z8/Global'),
  MR: z('Z8', 'Z8/Global'),
  MS: z('Z8', 'Z8/Global'),
  MU: z('Z8', 'Z8/Global'),
  MV: z('Z8', 'Z8/Global'),
  MW: z('Z8', 'Z8/Global'),
  MZ: z('Z8', 'Z8/Global'),
  NA: z('Z8', 'Z8/Global'),
  NC: z('Z8', 'Z8/Global'),
  NE: z('Z8', 'Z8/Global'),
  NG: z('Z8', 'Z8/Global'),
  NI: z('Z8', 'Z8/Global'),
  NP: z('Z8', 'Z8/Global'),
  NR: z('Z8', 'Z8/Global'),
  NU: z('Z8', 'Z8/Global'),
  PA: z('Z8', 'Z8/Global'),
  PE: z('Z8', 'Z8/Global'),
  PF: z('Z8', 'Z8/Global'),
  PR: z('Z8', 'Z8/Global'),
  PW: z('Z8', 'Z8/Global'),
  PY: z('Z8', 'Z8/Global'),
  RE: z('Z8', 'Z8/Global'),
  RU: z('Z8', 'Z8/Global'),
  RW: z('Z8', 'Z8/Global'),
  SB: z('Z8', 'Z8/Global'),
  SC: z('Z8', 'Z8/Global'),
  SD: z('Z8', 'Z8/Global'),
  SH: z('Z8', 'Z8/Global'),
  SL: z('Z8', 'Z8/Global'),
  SN: z('Z8', 'Z8/Global'),
  // SO (Somalia) removed — unshippable
  SR: z('Z8', 'Z8/Global'),
  SS: z('Z8', 'Z8/Global'),
  ST: z('Z8', 'Z8/Global'),
  SV: z('Z8', 'Z8/Global'),
  SY: z('Z8', 'Z8/Global'),
  SZ: z('Z8', 'Z8/Global'),
  TC: z('Z8', 'Z8/Global'),
  TD: z('Z8', 'Z8/Global'),
  TG: z('Z8', 'Z8/Global'),
  TJ: z('Z8', 'Z8/Global'),
  TL: z('Z8', 'Z8/Global'),
  TM: z('Z8', 'Z8/Global'),
  TN: z('Z8', 'Z8/Global'),
  TO: z('Z8', 'Z8/Global'),
  TT: z('Z8', 'Z8/Global'),
  TV: z('Z8', 'Z8/Global'),
  TZ: z('Z8', 'Z8/Global'),
  UA: z('Z8', 'Z8/Global'),
  UG: z('Z8', 'Z8/Global'),
  UY: z('Z8', 'Z8/Global'),
  UZ: z('Z8', 'Z8/Global'),
  VC: z('Z8', 'Z8/Global'),
  VE: z('Z8', 'Z8/Global'),
  VG: z('Z8', 'Z8/Global'),
  VI: z('Z8', 'Z8/Global'),
  VU: z('Z8', 'Z8/Global'),
  WS: z('Z8', 'Z8/Global'),
  YE: z('Z8', 'Z8/Global'),
  YT: z('Z8', 'Z8/Global'),
  ZA: z('Z8', 'Z8/Global'),
  ZM: z('Z8', 'Z8/Global'),
  ZW: z('Z8', 'Z8/Global'),
};

const DHL_DEFAULT_ZONE: ZoneInfo = { rateKey: 'Z8', label: 'Rest of World' };

export const determineDhlZone = (country: string): ZoneInfo =>
  DHL_ZONE_MAP[country] || DHL_DEFAULT_ZONE;
