export interface FlightSchedule {
  id: string;
  airline: string;
  airlineCode: string;
  flightNo: string;
  aircraftType: string;
  flightType: 'cargo' | 'passenger' | 'combi';
  origin: string;
  destination: string;
  departureDays: number[]; // 0=Sun, 1=Mon, ... 6=Sat
  departureTime: string;   // HH:MM (KST)
  arrivalTime: string;     // HH:MM (local)
  flightDuration: string;
  maxCargoKg: number;
  remarks?: string;
}

export type GssaGroup = 'goodman' | 'gac';

export interface AirlineInfo {
  code: string;
  name: string;
  nameKo: string;
  logo: string;
  country: string;
  hubCity: string;
  contractType: string;
  gssaGroup: GssaGroup; // 'goodman' = Goodman GLS, 'gac' = Globe Air Cargo (ECS Group)
}

export const GSSA_GROUP_LABELS = {
  goodman: { en: 'Goodman GLS', ko: 'Goodman GLS', badge: 'bg-jways-100 dark:bg-jways-900/40 text-jways-700 dark:text-jways-300 border-jways-200 dark:border-jways-700' },
  gac: { en: 'Globe Air Cargo (ECS)', ko: 'Globe Air Cargo (ECS)', badge: 'bg-purple-100 dark:bg-purple-900/40 text-purple-700 dark:text-purple-300 border-purple-200 dark:border-purple-700' },
} as const;

export const AIRLINE_INFO: AirlineInfo[] = [
  {
    code: 'WS',
    name: 'WestJet Cargo',
    nameKo: '웨스트젯 카고',
    logo: '🇨🇦',
    country: 'Canada',
    hubCity: 'Calgary (YYC)',
    contractType: 'GSSA — Cargo Sales Agent',
    gssaGroup: 'goodman',
  },
  {
    code: 'O3',
    name: 'ShunFeng Airlines',
    nameKo: '순펑항공 (SF Express)',
    logo: '🇨🇳',
    country: 'China',
    hubCity: 'Shenzhen (SZX)',
    contractType: 'GSSA — Cargo Sales Agent',
    gssaGroup: 'goodman',
  },
  {
    code: 'BX',
    name: 'Air Busan',
    nameKo: '에어부산',
    logo: '🇰🇷',
    country: 'South Korea',
    hubCity: 'Busan (PUS)',
    contractType: 'GSSA — Belly Cargo Sales',
    gssaGroup: 'goodman',
  },
  {
    code: 'M0',
    name: 'Aero Mongolia',
    nameKo: '에어로 몽골리아',
    logo: '🇲🇳',
    country: 'Mongolia',
    hubCity: 'Ulaanbaatar (UBN)',
    contractType: 'GSSA — Passenger & Cargo',
    gssaGroup: 'goodman',
  },
  {
    code: 'SU',
    name: 'Aeroflot',
    nameKo: '아에로플로트',
    logo: '🇷🇺',
    country: 'Russia',
    hubCity: 'Moscow (SVO)',
    contractType: 'GSSA — Currently Suspended',
    gssaGroup: 'goodman',
  },
  {
    code: '2C',
    name: 'CMA CGM Air Cargo',
    nameKo: 'CMA CGM 항공화물',
    logo: '🇫🇷',
    country: 'France',
    hubCity: 'Paris (CDG)',
    contractType: 'GSSA — Cargo Sales Agent (via Globe Air Cargo / ECS Group)',
    gssaGroup: 'gac',
  },
  {
    code: 'AM',
    name: 'Aeromexico Cargo',
    nameKo: '아에로멕시코 카고',
    logo: '🇲🇽',
    country: 'Mexico',
    hubCity: 'Mexico City (MEX)',
    contractType: 'GSSA — Cargo Sales Agent (via Globe Air Cargo / ECS Group)',
    gssaGroup: 'gac',
  },
  {
    code: 'YP',
    name: 'Air Premia',
    nameKo: '에어프레미아',
    logo: '🇰🇷',
    country: 'South Korea',
    hubCity: 'Seoul (ICN)',
    contractType: 'GSSA — Belly Cargo Sales',
    gssaGroup: 'goodman',
  },
  {
    code: 'DE',
    name: 'Condor Airlines',
    nameKo: '콘도르 항공',
    logo: '🇩🇪',
    country: 'Germany',
    hubCity: 'Frankfurt (FRA)',
    contractType: 'GSSA — Cargo Sales Agent (via Globe Air Cargo / ECS Group)',
    gssaGroup: 'gac',
  },
];

export const FLIGHT_SCHEDULES: FlightSchedule[] = [
  // WestJet Cargo (WS)
  {
    id: 'default-ws-7701',
    airline: 'WestJet Cargo',
    airlineCode: 'WS',
    flightNo: 'WS 7701',
    aircraftType: 'B737-800BCF',
    flightType: 'cargo',
    origin: 'ICN',
    destination: 'YYC',
    departureDays: [2, 4, 6],
    departureTime: '22:00',
    arrivalTime: '17:30',
    flightDuration: '10h 30m',
    maxCargoKg: 18000,
  },
  {
    id: 'default-ws-7703',
    airline: 'WestJet Cargo',
    airlineCode: 'WS',
    flightNo: 'WS 7703',
    aircraftType: 'B737-800BCF',
    flightType: 'cargo',
    origin: 'ICN',
    destination: 'YVR',
    departureDays: [1, 3, 5],
    departureTime: '23:00',
    arrivalTime: '16:00',
    flightDuration: '9h',
    maxCargoKg: 18000,
  },
  // ShunFeng Airlines (O3)
  {
    id: 'default-o3-6201',
    airline: 'ShunFeng Airlines',
    airlineCode: 'O3',
    flightNo: 'O3 6201',
    aircraftType: 'B757-200F',
    flightType: 'cargo',
    origin: 'ICN',
    destination: 'PVG',
    departureDays: [0, 1, 2, 3, 4, 5, 6],
    departureTime: '02:00',
    arrivalTime: '03:30',
    flightDuration: '2h 30m',
    maxCargoKg: 25000,
  },
  {
    id: 'default-o3-6203',
    airline: 'ShunFeng Airlines',
    airlineCode: 'O3',
    flightNo: 'O3 6203',
    aircraftType: 'B767-300F',
    flightType: 'cargo',
    origin: 'ICN',
    destination: 'SZX',
    departureDays: [0, 1, 3, 5],
    departureTime: '01:00',
    arrivalTime: '04:30',
    flightDuration: '4h 30m',
    maxCargoKg: 40000,
  },
  // Air Busan (BX)
  {
    id: 'default-bx-131',
    airline: 'Air Busan',
    airlineCode: 'BX',
    flightNo: 'BX 131',
    aircraftType: 'A321-200',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'FUK',
    departureDays: [0, 1, 2, 3, 4, 5, 6],
    departureTime: '09:30',
    arrivalTime: '11:00',
    flightDuration: '1h 30m',
    maxCargoKg: 2000,
    remarks: 'Belly cargo only',
  },
  {
    id: 'default-bx-173',
    airline: 'Air Busan',
    airlineCode: 'BX',
    flightNo: 'BX 173',
    aircraftType: 'A321-200',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'KIX',
    departureDays: [0, 1, 2, 3, 4, 5, 6],
    departureTime: '10:15',
    arrivalTime: '12:00',
    flightDuration: '2h',
    maxCargoKg: 2000,
    remarks: 'Belly cargo only',
  },
  {
    id: 'default-bx-741',
    airline: 'Air Busan',
    airlineCode: 'BX',
    flightNo: 'BX 741',
    aircraftType: 'A321-200',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'CEB',
    departureDays: [2, 4, 6],
    departureTime: '08:00',
    arrivalTime: '11:30',
    flightDuration: '4h 30m',
    maxCargoKg: 2000,
    remarks: 'Belly cargo only',
  },
  {
    id: 'default-bx-395',
    airline: 'Air Busan',
    airlineCode: 'BX',
    flightNo: 'BX 395',
    aircraftType: 'A321-200',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'NRT',
    departureDays: [0, 1, 2, 3, 4, 5, 6],
    departureTime: '14:00',
    arrivalTime: '16:20',
    flightDuration: '2h 20m',
    maxCargoKg: 2000,
    remarks: 'Belly cargo only',
  },
  // Aero Mongolia (M0)
  {
    id: 'default-m0-562',
    airline: 'Aero Mongolia',
    airlineCode: 'M0',
    flightNo: 'M0 562',
    aircraftType: 'B737-800',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'UBN',
    departureDays: [0, 1, 3, 5],
    departureTime: '10:00',
    arrivalTime: '12:30',
    flightDuration: '3h 30m',
    maxCargoKg: 3000,
  },
  {
    id: 'default-m0-564',
    airline: 'Aero Mongolia',
    airlineCode: 'M0',
    flightNo: 'M0 564',
    aircraftType: 'B737-800',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'UBN',
    departureDays: [2, 4, 6],
    departureTime: '15:00',
    arrivalTime: '17:30',
    flightDuration: '3h 30m',
    maxCargoKg: 3000,
  },
  // Aeroflot (SU) — suspended
  {
    id: 'default-su-251',
    airline: 'Aeroflot',
    airlineCode: 'SU',
    flightNo: 'SU 251',
    aircraftType: 'A330-300',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'SVO',
    departureDays: [1, 3, 5],
    departureTime: '18:30',
    arrivalTime: '21:00',
    flightDuration: '9h 30m',
    maxCargoKg: 15000,
    remarks: 'Currently SUSPENDED (sanctions)',
  },
  {
    id: 'default-su-253',
    airline: 'Aeroflot',
    airlineCode: 'SU',
    flightNo: 'SU 253',
    aircraftType: 'B777-300ER',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'SVO',
    departureDays: [0, 2, 4, 6],
    departureTime: '19:00',
    arrivalTime: '21:30',
    flightDuration: '9h 30m',
    maxCargoKg: 20000,
    remarks: 'Currently SUSPENDED (sanctions)',
  },
  // CMA CGM Air Cargo (2C) — operated as 5Y, AWB prefix 003
  {
    id: 'default-5y-8527',
    airline: 'CMA CGM Air Cargo',
    airlineCode: '2C',
    flightNo: '5Y 8527',
    aircraftType: 'B777-200F',
    flightType: 'cargo',
    origin: 'ICN',
    destination: 'HAN',
    departureDays: [2], // D3 = Tuesday
    departureTime: '21:45',
    arrivalTime: '00:55',
    flightDuration: '4h 10m',
    maxCargoKg: 100000,
    remarks: 'AACT T1 · Cut-off 4h prior (1445L) · AWB: 003',
  },
  {
    id: 'default-5y-8529',
    airline: 'CMA CGM Air Cargo',
    airlineCode: '2C',
    flightNo: '5Y 8529',
    aircraftType: 'B777-200F',
    flightType: 'cargo',
    origin: 'ICN',
    destination: 'HAN',
    departureDays: [4], // D5 = Thursday
    departureTime: '18:45',
    arrivalTime: '21:55',
    flightDuration: '4h 10m',
    maxCargoKg: 100000,
    remarks: 'AACT T1 · Cut-off 4h prior (1445L) · AWB: 003',
  },
  {
    id: 'default-5y-8531',
    airline: 'CMA CGM Air Cargo',
    airlineCode: '2C',
    flightNo: '5Y 8531',
    aircraftType: 'B777-200F',
    flightType: 'cargo',
    origin: 'ICN',
    destination: 'HAN',
    departureDays: [6], // D7 = Saturday
    departureTime: '18:45',
    arrivalTime: '21:55',
    flightDuration: '4h 10m',
    maxCargoKg: 100000,
    remarks: 'AACT T1 · Cut-off 4h prior (1445L) · AWB: 003',
  },
  // Aeromexico Cargo (AM) — via Globe Air Cargo / ECS Group
  {
    id: 'default-am-091',
    airline: 'Aeromexico Cargo',
    airlineCode: 'AM',
    flightNo: 'AM 091',
    aircraftType: 'B787-8/9',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'MEX',
    departureDays: [0, 1, 3, 5, 6], // D13567
    departureTime: '13:30',
    arrivalTime: '12:20',
    flightDuration: '13h 50m',
    maxCargoKg: 15000,
    remarks: 'Belly cargo · Via MEX → MTY/GDL(MX), GRU/EZE/SCL/LIM/BOG/MDE/GUA/SJO/SDQ(S.Am)',
  },
  // Air Premia (YP) — Effective 2026.03.29~, B787-9, belly cargo
  {
    id: 'default-yp-101',
    airline: 'Air Premia',
    airlineCode: 'YP',
    flightNo: 'YP 101',
    aircraftType: 'B787-9',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'LAX',
    departureDays: [0, 1, 2, 3, 4, 5, 6], // Daily
    departureTime: '13:00',
    arrivalTime: '08:20',
    flightDuration: '11h 20m',
    maxCargoKg: 15000,
    remarks: 'Belly cargo · Swissport ICN T-B',
  },
  {
    id: 'default-yp-103',
    airline: 'Air Premia',
    airlineCode: 'YP',
    flightNo: 'YP 103',
    aircraftType: 'B787-9',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'LAX',
    departureDays: [0, 1, 3, 5], // Mon/Wed/Fri/Sun
    departureTime: '22:05',
    arrivalTime: '17:20',
    flightDuration: '11h 15m',
    maxCargoKg: 15000,
    remarks: 'Belly cargo · 2nd daily LAX',
  },
  {
    id: 'default-yp-131',
    airline: 'Air Premia',
    airlineCode: 'YP',
    flightNo: 'YP 131',
    aircraftType: 'B787-9',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'EWR',
    departureDays: [0, 1, 2, 3, 4, 5, 6], // Daily
    departureTime: '21:25',
    arrivalTime: '22:30',
    flightDuration: '14h 05m',
    maxCargoKg: 15000,
    remarks: 'Belly cargo · Newark (New York)',
  },
  {
    id: 'default-yp-111',
    airline: 'Air Premia',
    airlineCode: 'YP',
    flightNo: 'YP 111',
    aircraftType: 'B787-9',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'SFO',
    departureDays: [0, 1, 3, 5], // Mon/Wed/Fri/Sun
    departureTime: '18:00',
    arrivalTime: '13:00',
    flightDuration: '10h',
    maxCargoKg: 15000,
    remarks: 'Belly cargo',
  },
  {
    id: 'default-yp-151',
    airline: 'Air Premia',
    airlineCode: 'YP',
    flightNo: 'YP 151',
    aircraftType: 'B787-9',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'HNL',
    departureDays: [0, 1, 3, 5], // Mon/Wed/Fri/Sun
    departureTime: '22:30',
    arrivalTime: '12:20',
    flightDuration: '7h 50m',
    maxCargoKg: 15000,
    remarks: 'Belly cargo · Honolulu',
  },
  {
    id: 'default-yp-731',
    airline: 'Air Premia',
    airlineCode: 'YP',
    flightNo: 'YP 731',
    aircraftType: 'B787-9',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'NRT',
    departureDays: [0, 1, 3, 4, 5, 6], // Daily except Tue (Tue=YP733)
    departureTime: '08:50',
    arrivalTime: '11:20',
    flightDuration: '2h 30m',
    maxCargoKg: 15000,
    remarks: 'Belly cargo · Narita',
  },
  {
    id: 'default-yp-735',
    airline: 'Air Premia',
    airlineCode: 'YP',
    flightNo: 'YP 735',
    aircraftType: 'B787-9',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'NRT',
    departureDays: [1, 5, 0], // Mon/Fri/Sun (from 3/29)
    departureTime: '13:50',
    arrivalTime: '16:30',
    flightDuration: '2h 40m',
    maxCargoKg: 15000,
    remarks: 'Belly cargo · 2nd daily NRT (from 3/29)',
  },
  {
    id: 'default-yp-601',
    airline: 'Air Premia',
    airlineCode: 'YP',
    flightNo: 'YP 601',
    aircraftType: 'B787-9',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'BKK',
    departureDays: [0, 1, 2, 4, 5], // Mon/Tue/Thu/Fri/Sun
    departureTime: '17:15',
    arrivalTime: '21:10',
    flightDuration: '5h 55m',
    maxCargoKg: 15000,
    remarks: 'Belly cargo · Bangkok',
  },
  {
    id: 'default-yp-621',
    airline: 'Air Premia',
    airlineCode: 'YP',
    flightNo: 'YP 621',
    aircraftType: 'B787-9',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'DAD',
    departureDays: [0, 3, 4, 6], // Wed/Thu/Sat/Sun
    departureTime: '17:45',
    arrivalTime: '20:40',
    flightDuration: '4h 55m',
    maxCargoKg: 15000,
    remarks: 'Belly cargo · Da Nang',
  },
  {
    id: 'default-yp-801',
    airline: 'Air Premia',
    airlineCode: 'YP',
    flightNo: 'YP 801',
    aircraftType: 'B787-9',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'HKG',
    departureDays: [0, 1, 3, 5], // Mon/Wed/Fri/Sun
    departureTime: '09:15',
    arrivalTime: '12:00',
    flightDuration: '3h 45m',
    maxCargoKg: 15000,
    remarks: 'Belly cargo · Hong Kong',
  },
  // Condor Airlines (DE)
  {
    id: 'default-de-2025',
    airline: 'Condor Airlines',
    airlineCode: 'DE',
    flightNo: 'DE 2025',
    aircraftType: 'A330-900neo',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'FRA',
    departureDays: [2, 4, 6],
    departureTime: '13:00',
    arrivalTime: '18:30',
    flightDuration: '11h 30m',
    maxCargoKg: 10000,
    remarks: 'Seasonal (Summer IATA schedule)',
  },
  {
    id: 'default-de-2027',
    airline: 'Condor Airlines',
    airlineCode: 'DE',
    flightNo: 'DE 2027',
    aircraftType: 'A330-900neo',
    flightType: 'passenger',
    origin: 'ICN',
    destination: 'FRA',
    departureDays: [1, 3, 5],
    departureTime: '14:30',
    arrivalTime: '20:00',
    flightDuration: '11h 30m',
    maxCargoKg: 10000,
    remarks: 'Seasonal (Summer IATA schedule)',
  },
];

/** Color classes per airline code */
export const AIRLINE_COLORS: Record<string, { bg: string; text: string; border: string; badge: string }> = {
  WS: {
    bg: 'bg-teal-50 dark:bg-teal-900/20',
    text: 'text-teal-700 dark:text-teal-300',
    border: 'border-teal-200 dark:border-teal-800',
    badge: 'bg-teal-100 dark:bg-teal-900/40 text-teal-700 dark:text-teal-300',
  },
  O3: {
    bg: 'bg-orange-50 dark:bg-orange-900/20',
    text: 'text-orange-700 dark:text-orange-300',
    border: 'border-orange-200 dark:border-orange-800',
    badge: 'bg-orange-100 dark:bg-orange-900/40 text-orange-700 dark:text-orange-300',
  },
  BX: {
    bg: 'bg-blue-50 dark:bg-blue-900/20',
    text: 'text-blue-700 dark:text-blue-300',
    border: 'border-blue-200 dark:border-blue-800',
    badge: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300',
  },
  M0: {
    bg: 'bg-sky-50 dark:bg-sky-900/20',
    text: 'text-sky-700 dark:text-sky-300',
    border: 'border-sky-200 dark:border-sky-800',
    badge: 'bg-sky-100 dark:bg-sky-900/40 text-sky-700 dark:text-sky-300',
  },
  SU: {
    bg: 'bg-red-50 dark:bg-red-900/20',
    text: 'text-red-700 dark:text-red-300',
    border: 'border-red-200 dark:border-red-800',
    badge: 'bg-red-100 dark:bg-red-900/40 text-red-700 dark:text-red-300',
  },
  '2C': {
    bg: 'bg-rose-50 dark:bg-rose-900/20',
    text: 'text-rose-700 dark:text-rose-300',
    border: 'border-rose-200 dark:border-rose-800',
    badge: 'bg-rose-100 dark:bg-rose-900/40 text-rose-700 dark:text-rose-300',
  },
  AM: {
    bg: 'bg-emerald-50 dark:bg-emerald-900/20',
    text: 'text-emerald-700 dark:text-emerald-300',
    border: 'border-emerald-200 dark:border-emerald-800',
    badge: 'bg-emerald-100 dark:bg-emerald-900/40 text-emerald-700 dark:text-emerald-300',
  },
  YP: {
    bg: 'bg-violet-50 dark:bg-violet-900/20',
    text: 'text-violet-700 dark:text-violet-300',
    border: 'border-violet-200 dark:border-violet-800',
    badge: 'bg-violet-100 dark:bg-violet-900/40 text-violet-700 dark:text-violet-300',
  },
  DE: {
    bg: 'bg-yellow-50 dark:bg-yellow-900/20',
    text: 'text-yellow-700 dark:text-yellow-300',
    border: 'border-yellow-200 dark:border-yellow-800',
    badge: 'bg-yellow-100 dark:bg-yellow-900/40 text-yellow-700 dark:text-yellow-300',
  },
};

/** Day labels for display */
export const DAY_LABELS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] as const;
export const DAY_LABELS_KO = ['일', '월', '화', '수', '목', '금', '토'] as const;
