/**
 * UPS zone mapping: country code -> { rateKey, label }
 * Source: Zone Guide 2026.xlsx (UPS sheet)
 * Auto-synced with UPS_ZONE_COUNTRIES in options.ts
 */

export type ZoneInfo = { rateKey: string; label: string };

const z = (rateKey: string, label: string): ZoneInfo => ({ rateKey, label });

export const UPS_ZONE_MAP: Record<string, ZoneInfo> = {
  // Z1: CN, MO, SG, TW
  CN: z('Z1', 'Z1/Asia'),
  MO: z('Z1', 'Z1/Asia'),
  SG: z('Z1', 'Z1/Asia'),
  TW: z('Z1', 'Z1/Asia'),
  // Z2: JP, VN
  JP: z('Z2', 'Z2/JP-VN'),
  VN: z('Z2', 'Z2/JP-VN'),
  // Z3: BN, ID, MY, PH, TH
  BN: z('Z3', 'Z3/SEA'),
  ID: z('Z3', 'Z3/SEA'),
  MY: z('Z3', 'Z3/SEA'),
  PH: z('Z3', 'Z3/SEA'),
  TH: z('Z3', 'Z3/SEA'),
  // Z4: AU, IN, NF, NZ
  AU: z('Z4', 'Z4/Oceania'),
  IN: z('Z4', 'Z4/Oceania'),
  NF: z('Z4', 'Z4/Oceania'),
  NZ: z('Z4', 'Z4/Oceania'),
  // Z5: CA, MX, PR, US
  CA: z('Z5', 'Z5/Americas'),
  MX: z('Z5', 'Z5/Americas'),
  PR: z('Z5', 'Z5/Americas'),
  US: z('Z5', 'Z5/Americas'),
  // Z6: AD, BE, CH, CZ, DE, ES, FR, GB, IC, IT, LI, LU, MC, NL, PL, SE, SK, SM, VA
  AD: z('Z6', 'Z6/W.Europe'),
  BE: z('Z6', 'Z6/W.Europe'),
  CH: z('Z6', 'Z6/W.Europe'),
  CZ: z('Z6', 'Z6/W.Europe'),
  DE: z('Z6', 'Z6/W.Europe'),
  ES: z('Z6', 'Z6/W.Europe'),
  FR: z('Z6', 'Z6/W.Europe'),
  GB: z('Z6', 'Z6/W.Europe'),
  IC: z('Z6', 'Z6/W.Europe'),
  IT: z('Z6', 'Z6/W.Europe'),
  LI: z('Z6', 'Z6/W.Europe'),
  LU: z('Z6', 'Z6/W.Europe'),
  MC: z('Z6', 'Z6/W.Europe'),
  NL: z('Z6', 'Z6/W.Europe'),
  PL: z('Z6', 'Z6/W.Europe'),
  SE: z('Z6', 'Z6/W.Europe'),
  SK: z('Z6', 'Z6/W.Europe'),
  SM: z('Z6', 'Z6/W.Europe'),
  VA: z('Z6', 'Z6/W.Europe'),
  // Z7: AT, AX, DK, FI, GR, IE, NO, PT
  AT: z('Z7', 'Z7/N.Europe'),
  AX: z('Z7', 'Z7/N.Europe'),
  DK: z('Z7', 'Z7/N.Europe'),
  FI: z('Z7', 'Z7/N.Europe'),
  GR: z('Z7', 'Z7/N.Europe'),
  IE: z('Z7', 'Z7/N.Europe'),
  NO: z('Z7', 'Z7/N.Europe'),
  PT: z('Z7', 'Z7/N.Europe'),
  // Z8 (78 countries)
  AE: z('Z8', 'Z8/Global'),
  AG: z('Z8', 'Z8/Global'),
  AI: z('Z8', 'Z8/Global'),
  AR: z('Z8', 'Z8/Global'),
  AW: z('Z8', 'Z8/Global'),
  AZ: z('Z8', 'Z8/Global'),
  BB: z('Z8', 'Z8/Global'),
  BD: z('Z8', 'Z8/Global'),
  BG: z('Z8', 'Z8/Global'),
  BH: z('Z8', 'Z8/Global'),
  BL: z('Z8', 'Z8/Global'),
  BO: z('Z8', 'Z8/Global'),
  BQ: z('Z8', 'Z8/Global'),
  BR: z('Z8', 'Z8/Global'),
  BS: z('Z8', 'Z8/Global'),
  BZ: z('Z8', 'Z8/Global'),
  CL: z('Z8', 'Z8/Global'),
  CO: z('Z8', 'Z8/Global'),
  CR: z('Z8', 'Z8/Global'),
  CW: z('Z8', 'Z8/Global'),
  CY: z('Z8', 'Z8/Global'),
  DM: z('Z8', 'Z8/Global'),
  DO: z('Z8', 'Z8/Global'),
  EC: z('Z8', 'Z8/Global'),
  EG: z('Z8', 'Z8/Global'),
  ER: z('Z8', 'Z8/Global'),
  GD: z('Z8', 'Z8/Global'),
  GF: z('Z8', 'Z8/Global'),
  GG: z('Z8', 'Z8/Global'),
  GI: z('Z8', 'Z8/Global'),
  GP: z('Z8', 'Z8/Global'),
  GT: z('Z8', 'Z8/Global'),
  GU: z('Z8', 'Z8/Global'),
  HN: z('Z8', 'Z8/Global'),
  HR: z('Z8', 'Z8/Global'),
  HT: z('Z8', 'Z8/Global'),
  HU: z('Z8', 'Z8/Global'),
  IS: z('Z8', 'Z8/Global'),
  JE: z('Z8', 'Z8/Global'),
  JM: z('Z8', 'Z8/Global'),
  KH: z('Z8', 'Z8/Global'),
  KN: z('Z8', 'Z8/Global'),
  KW: z('Z8', 'Z8/Global'),
  KY: z('Z8', 'Z8/Global'),
  LA: z('Z8', 'Z8/Global'),
  LC: z('Z8', 'Z8/Global'),
  LK: z('Z8', 'Z8/Global'),
  LT: z('Z8', 'Z8/Global'),
  LV: z('Z8', 'Z8/Global'),
  MM: z('Z8', 'Z8/Global'),
  MQ: z('Z8', 'Z8/Global'),
  MS: z('Z8', 'Z8/Global'),
  MT: z('Z8', 'Z8/Global'),
  MV: z('Z8', 'Z8/Global'),
  NI: z('Z8', 'Z8/Global'),
  OM: z('Z8', 'Z8/Global'),
  PA: z('Z8', 'Z8/Global'),
  PE: z('Z8', 'Z8/Global'),
  PK: z('Z8', 'Z8/Global'),
  PY: z('Z8', 'Z8/Global'),
  QA: z('Z8', 'Z8/Global'),
  RO: z('Z8', 'Z8/Global'),
  RU: z('Z8', 'Z8/Global'),
  SA: z('Z8', 'Z8/Global'),
  SI: z('Z8', 'Z8/Global'),
  SR: z('Z8', 'Z8/Global'),
  SV: z('Z8', 'Z8/Global'),
  SX: z('Z8', 'Z8/Global'),
  TC: z('Z8', 'Z8/Global'),
  TR: z('Z8', 'Z8/Global'),
  TT: z('Z8', 'Z8/Global'),
  UA: z('Z8', 'Z8/Global'),
  UY: z('Z8', 'Z8/Global'),
  VC: z('Z8', 'Z8/Global'),
  VE: z('Z8', 'Z8/Global'),
  VG: z('Z8', 'Z8/Global'),
  VI: z('Z8', 'Z8/Global'),
  ZA: z('Z8', 'Z8/Global'),
  // Z9 (77 countries)
  AF: z('Z9', 'Z9/Extended'),
  AL: z('Z9', 'Z9/Extended'),
  AM: z('Z9', 'Z9/Extended'),
  AO: z('Z9', 'Z9/Extended'),
  AS: z('Z9', 'Z9/Extended'),
  BA: z('Z9', 'Z9/Extended'),
  BF: z('Z9', 'Z9/Extended'),
  BI: z('Z9', 'Z9/Extended'),
  BJ: z('Z9', 'Z9/Extended'),
  BM: z('Z9', 'Z9/Extended'),
  BW: z('Z9', 'Z9/Extended'),
  BY: z('Z9', 'Z9/Extended'),
  CD: z('Z9', 'Z9/Extended'),
  CF: z('Z9', 'Z9/Extended'),
  CG: z('Z9', 'Z9/Extended'),
  CI: z('Z9', 'Z9/Extended'),
  CM: z('Z9', 'Z9/Extended'),
  CV: z('Z9', 'Z9/Extended'),
  DJ: z('Z9', 'Z9/Extended'),
  DZ: z('Z9', 'Z9/Extended'),
  EE: z('Z9', 'Z9/Extended'),
  ET: z('Z9', 'Z9/Extended'),
  FO: z('Z9', 'Z9/Extended'),
  GA: z('Z9', 'Z9/Extended'),
  GE: z('Z9', 'Z9/Extended'),
  GH: z('Z9', 'Z9/Extended'),
  GL: z('Z9', 'Z9/Extended'),
  GM: z('Z9', 'Z9/Extended'),
  GN: z('Z9', 'Z9/Extended'),
  GQ: z('Z9', 'Z9/Extended'),
  GW: z('Z9', 'Z9/Extended'),
  GY: z('Z9', 'Z9/Extended'),
  IL: z('Z9', 'Z9/Extended'),
  IQ: z('Z9', 'Z9/Extended'),
  JO: z('Z9', 'Z9/Extended'),
  KE: z('Z9', 'Z9/Extended'),
  KG: z('Z9', 'Z9/Extended'),
  KM: z('Z9', 'Z9/Extended'),
  KZ: z('Z9', 'Z9/Extended'),
  LB: z('Z9', 'Z9/Extended'),
  LR: z('Z9', 'Z9/Extended'),
  LS: z('Z9', 'Z9/Extended'),
  MA: z('Z9', 'Z9/Extended'),
  MD: z('Z9', 'Z9/Extended'),
  ME: z('Z9', 'Z9/Extended'),
  MG: z('Z9', 'Z9/Extended'),
  MK: z('Z9', 'Z9/Extended'),
  ML: z('Z9', 'Z9/Extended'),
  MN: z('Z9', 'Z9/Extended'),
  MP: z('Z9', 'Z9/Extended'),
  MR: z('Z9', 'Z9/Extended'),
  MU: z('Z9', 'Z9/Extended'),
  MW: z('Z9', 'Z9/Extended'),
  MZ: z('Z9', 'Z9/Extended'),
  NA: z('Z9', 'Z9/Extended'),
  NC: z('Z9', 'Z9/Extended'),
  NE: z('Z9', 'Z9/Extended'),
  NG: z('Z9', 'Z9/Extended'),
  NP: z('Z9', 'Z9/Extended'),
  RE: z('Z9', 'Z9/Extended'),
  RS: z('Z9', 'Z9/Extended'),
  RW: z('Z9', 'Z9/Extended'),
  SC: z('Z9', 'Z9/Extended'),
  SL: z('Z9', 'Z9/Extended'),
  SN: z('Z9', 'Z9/Extended'),
  SZ: z('Z9', 'Z9/Extended'),
  TD: z('Z9', 'Z9/Extended'),
  TG: z('Z9', 'Z9/Extended'),
  TM: z('Z9', 'Z9/Extended'),
  TN: z('Z9', 'Z9/Extended'),
  TZ: z('Z9', 'Z9/Extended'),
  UG: z('Z9', 'Z9/Extended'),
  UZ: z('Z9', 'Z9/Extended'),
  WS: z('Z9', 'Z9/Extended'),
  YT: z('Z9', 'Z9/Extended'),
  ZM: z('Z9', 'Z9/Extended'),
  ZW: z('Z9', 'Z9/Extended'),
  // Z10: HK, SO
  HK: z('Z10', 'Z10/HK'),
  SO: z('Z10', 'Z10/S.China'),
};

const UPS_DEFAULT_ZONE: ZoneInfo = { rateKey: 'Z10', label: 'Rest of World' };

export const determineUpsZone = (country: string): ZoneInfo =>
  UPS_ZONE_MAP[country] || UPS_DEFAULT_ZONE;
